// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/authz.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Authz struct {
	Resource             string   `protobuf:"bytes,71933,opt,name=resource,proto3" json:"resource,omitempty"`
	Action               string   `protobuf:"bytes,71934,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Authz) Reset()         { *m = Authz{} }
func (m *Authz) String() string { return proto.CompactTextString(m) }
func (*Authz) ProtoMessage()    {}
func (*Authz) Descriptor() ([]byte, []int) {
	return fileDescriptor_00552c9305953ea0, []int{0}
}

func (m *Authz) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authz.Unmarshal(m, b)
}
func (m *Authz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authz.Marshal(b, m, deterministic)
}
func (m *Authz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authz.Merge(m, src)
}
func (m *Authz) XXX_Size() int {
	return xxx_messageInfo_Authz.Size(m)
}
func (m *Authz) XXX_DiscardUnknown() {
	xxx_messageInfo_Authz.DiscardUnknown(m)
}

var xxx_messageInfo_Authz proto.InternalMessageInfo

func (m *Authz) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *Authz) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func init() {
	proto.RegisterType((*Authz)(nil), "api.Authz")
}

func init() { proto.RegisterFile("api/authz.proto", fileDescriptor_00552c9305953ea0) }

var fileDescriptor_00552c9305953ea0 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x2c, 0xc8, 0xd4,
	0x4f, 0x2c, 0x2d, 0xc9, 0xa8, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8,
	0x94, 0x52, 0x48, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b, 0x25, 0x95, 0xa6, 0xe9, 0xa7,
	0xa4, 0x16, 0x27, 0x17, 0x65, 0x16, 0x94, 0xe4, 0x17, 0x41, 0x94, 0x29, 0xd9, 0x73, 0xb1, 0x3a,
	0x82, 0x74, 0x09, 0xc9, 0x70, 0x71, 0x14, 0xa5, 0x16, 0xe7, 0x97, 0x16, 0x25, 0xa7, 0x4a, 0xfc,
	0xdd, 0xc8, 0xa2, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x17, 0x11, 0x92, 0xe0, 0x62, 0x4b, 0x4c, 0x2e,
	0xc9, 0xcc, 0xcf, 0x93, 0xf8, 0x07, 0x95, 0x83, 0xf2, 0x9d, 0x14, 0xa2, 0xe4, 0xd2, 0x33, 0x4b,
	0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x93, 0xf3, 0x12, 0x4b, 0x32, 0xcb, 0x52, 0xf5,
	0x0b, 0xb2, 0xd3, 0xf5, 0x13, 0x0b, 0x32, 0xad, 0x13, 0x0b, 0x32, 0x93, 0xd8, 0xc0, 0x36, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x4c, 0xdd, 0x44, 0xa3, 0x00, 0x00, 0x00,
}
